<?php

use Illuminate\Database\Seeder;
use App\Models\Region;

class RegionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $createRegion = new Region;
        $createRegion->id = '1';
        $createRegion->name = 'Hà Nam 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '2';
        $createRegion->name = 'Hà Nam 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '3';
        $createRegion->name = 'Hà Nam 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '4';
        $createRegion->name = 'Hà Nam 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '5';
        $createRegion->name = 'Hà Nam 5';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '6';
        $createRegion->name = 'Hà Nam 6';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '7';
        $createRegion->name = 'Hà Nam 7';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '8';
        $createRegion->name = 'Hà Nam 8';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '9';
        $createRegion->name = 'Hà Nam 9';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '10';
        $createRegion->name = 'Hà Nam 10';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '11';
        $createRegion->name = 'Ninh Bình 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '12';
        $createRegion->name = 'Ninh Bình 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '13';
        $createRegion->name = 'Ninh Bình 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '14';
        $createRegion->name = 'Nam Định 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '15';
        $createRegion->name = 'Nam Định 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '16';
        $createRegion->name = 'Nam Định 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '17';
        $createRegion->name = 'Nam Định 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '18';
        $createRegion->name = 'Thái Bình 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '19';
        $createRegion->name = 'Thái Bình 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '20';
        $createRegion->name = 'Thái Bình 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '21';
        $createRegion->name = 'Thái Bình 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '22';
        $createRegion->name = 'Thanh Hóa 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '23';
        $createRegion->name = 'Thanh Hóa 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '24';
        $createRegion->name = 'Thanh Hóa 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '25';
        $createRegion->name = 'Thanh Hóa 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '26';
        $createRegion->name = 'Thanh Hóa 5';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '27';
        $createRegion->name = 'Thanh Hóa 6';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '28';
        $createRegion->name = 'Lào Cai';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '29';
        $createRegion->name = 'Yên Bái';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '30';
        $createRegion->name = 'Phú Thọ 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '31';
        $createRegion->name = 'Phú Thọ 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '32';
        $createRegion->name = 'Phú Thọ 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '33';
        $createRegion->name = 'Phú Thọ 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '34';
        $createRegion->name = 'Phú Thọ 5';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '35';
        $createRegion->name = 'Phú Thọ 6';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '36';
        $createRegion->name = 'Phú Thọ 7';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '37';
        $createRegion->name = 'Phú Thọ 8';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '38';
        $createRegion->name = 'Phú Thọ 9';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '39';
        $createRegion->name = 'Tuyên Quang';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '40';
        $createRegion->name = 'Bắc Ninh 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '41';
        $createRegion->name = 'Bắc Ninh 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '42';
        $createRegion->name = 'Đông Anh';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '43';
        $createRegion->name = 'Sóc Sơn';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '44';
        $createRegion->name = 'Bắc Giang 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '45';
        $createRegion->name = 'Bắc Giang 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '46';
        $createRegion->name = 'Bắc Giang 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '47';
        $createRegion->name = 'Bắc Giang 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion->name = 'Bắc Giang 5';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '48';
        $createRegion->name = 'Bắc Giang 6';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '49';
        $createRegion->name = 'Bắc Giang 7';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '50';
        $createRegion->name = 'Bắc Giang 8';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '51';
        $createRegion->name = 'Bắc Giang 9';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '52';
        $createRegion->name = 'Lạng Sơn';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '53';
        $createRegion->name = 'Vĩnh Phúc 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '54';
        $createRegion->name = 'Vĩnh Phúc 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '55';
        $createRegion->name = 'Vĩnh Phúc 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '56';
        $createRegion->name = 'Vĩnh Phúc 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '57';
        $createRegion->name = 'Vĩnh Phúc 5';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '58';
        $createRegion->name = 'Vĩnh Phúc 6';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '59';
        $createRegion->name = 'Vĩnh Phúc 7';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '60';
        $createRegion->name = 'Vĩnh Phúc 8';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '61';
        $createRegion->name = 'Vĩnh Phúc 9';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '62';
        $createRegion->name = 'Vĩnh Phúc 10';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '63';
        $createRegion->name = 'Vĩnh Phúc 11';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '64';
        $createRegion->name = 'Vĩnh Phúc 12';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '65';
        $createRegion->name = 'Vĩnh Phúc 13';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '66';
        $createRegion->name = 'Vĩnh Phúc 14';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '67';
        $createRegion->name = 'Thái Nguyên 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '68';
        $createRegion->name = 'Thái Nguyên 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '69';
        $createRegion->name = 'Thái Nguyên 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '70';
        $createRegion->name = 'Thái Nguyên 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '71';
        $createRegion->name = 'Thái Nguyên 5';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '72';
        $createRegion->name = 'Thái Nguyên 6';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '73';
        $createRegion->name = 'Quảng Ninh';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '74';
        $createRegion->name = 'Hưng Yên 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '75';
        $createRegion->name = 'Hưng Yên 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '76';
        $createRegion->name = 'Hưng Yên 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '77';
        $createRegion->name = 'Hưng Yên 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '78';
        $createRegion->name = 'Hải Dương 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '79';
        $createRegion->name = 'Hải Dương 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '80';
        $createRegion->name = 'Hải Dương 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '81';
        $createRegion->name = 'Hải Dương 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '82';
        $createRegion->name = 'Hải Dương 5';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '83';
        $createRegion->name = 'Hải Dương 6';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '84';
        $createRegion->name = 'Hải Phòng 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '85';
        $createRegion->name = 'Hải Phòng 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '86';
        $createRegion->name = 'Hải Phòng 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '87';
        $createRegion->name = 'Hải Phòng 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '88';
        $createRegion->name = 'Hòa Bình 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '89';
        $createRegion->name = 'Hòa Bình 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '90';
        $createRegion->name = 'Hòa Bình 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '91';
        $createRegion->name = 'Hà Tây 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '92';
        $createRegion->name = 'Hà Tây 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '93';
        $createRegion->name = 'Hà Tây 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '94';
        $createRegion->name = 'Hà Tây 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '95';
        $createRegion->name = 'Hà Tây 5';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '96';
        $createRegion->name = 'Hà Tây 6';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '97';
        $createRegion->name = 'Hà Tây 7';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '98';
        $createRegion->name = 'Hà Tây 8';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '99';
        $createRegion->name = 'Hà Tây 9';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '100';
        $createRegion->name = 'Hà Tây 10';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '101';
        $createRegion->name = 'Hà Tây 11';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '102';
        $createRegion->name = 'Hà Tây 12';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '103';
        $createRegion->name = 'Hà Tây 13';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '104';
        $createRegion->name = 'Hà Tây 14';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '105';
        $createRegion->name = 'Hà Tây 15';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '106';
        $createRegion->name = 'Hà Tây 16';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '107';
        $createRegion->name = 'Hà Tây 17';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '108';
        $createRegion->name = 'Hà Tây 18';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '109';
        $createRegion->name = 'Hà Tây 19';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '110';
        $createRegion->name = 'Sơn La 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '111';
        $createRegion->name = 'Sơn La 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '112';
        $createRegion->name = 'Điện Biên 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '113';
        $createRegion->name = 'Điện Biên 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '114';
        $createRegion->name = 'Nghệ An 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '115';
        $createRegion->name = 'Nghệ An 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '116';
        $createRegion->name = 'Nghệ An 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '117';
        $createRegion->name = 'Nghệ An 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '118';
        $createRegion->name = 'Hà Tĩnh 1';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '119';
        $createRegion->name = 'Hà Tĩnh 2';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '120';
        $createRegion->name = 'Hà Tĩnh 3';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '121';
        $createRegion->name = 'Hà Tĩnh 4';
        $createRegion->manager_id = 11;
        $createRegion->save();
        $createRegion = new Region;
        $createRegion->id = '122';
        $createRegion->name = 'Quảng Bình';
        $createRegion->manager_id = 11;
        $createRegion->save();
    }
}
